"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.BleEvent = void 0;
let BleEvent;
exports.BleEvent = BleEvent;
(function (BleEvent) {
  BleEvent["EVENT_MESH_NETWORK_CONNECTION"] = "EVENT_MESH_NETWORK_CONNECTION";
  BleEvent["EVENT_DEVICE_FOUND"] = "EVENT_DEVICE_FOUND";
  BleEvent["EVENT_SCANNING_TIMEOUT"] = "EVENT_SCANNING_TIMEOUT";
  BleEvent["EVENT_SET_GROUP_SUCCESS"] = "EVENT_SET_GROUP_SUCCESS";
  BleEvent["EVENT_SET_GROUP_FAILED"] = "EVENT_SET_GROUP_FAILED";
  BleEvent["EVENT_SET_SCENE_SUCCESS"] = "EVENT_SET_SCENE_SUCCESS";
  BleEvent["EVENT_SET_SCENE_FAILED"] = "EVENT_SET_SCENE_FAILED";
  BleEvent["EVENT_DEVICE_STATUS"] = "EVENT_DEVICE_STATUS";
  BleEvent["EVENT_DEVICE_ONLINE"] = "EVENT_DEVICE_ONLINE";
  BleEvent["EVENT_BINDING_SUCCESS"] = "EVENT_BINDING_SUCCESS";
  BleEvent["EVENT_NODE_RESET_SUCCESS"] = "EVENT_NODE_RESET_SUCCESS";
  BleEvent["EVENT_NODE_RESET_FAILED"] = "EVENT_NODE_RESET_FAILED";
  BleEvent["EVENT_ANDROID_SCAN_FINISH"] = "EVENT_ANDROID_SCAN_FINISH";
  BleEvent["EVENT_TYPE_NOTIFICATION_MESSAGE_UNKNOWN"] = "EVENT_TYPE_NOTIFICATION_MESSAGE_UNKNOWN";
  BleEvent["EVENT_TYPE_OTA_FAIL"] = "EVENT_TYPE_OTA_FAIL";
  BleEvent["EVENT_TYPE_OTA_SUCCESS"] = "EVENT_TYPE_OTA_SUCCESS";
  BleEvent["EVENT_TYPE_OTA_PROGRESS"] = "EVENT_TYPE_OTA_PROGRESS";
})(BleEvent || (exports.BleEvent = BleEvent = {}));
//# sourceMappingURL=BleEvent.js.map