export enum BleEvent {
  EVENT_MESH_NETWORK_CONNECTION = 'EVENT_MESH_NETWORK_CONNECTION',

  EVENT_DEVICE_FOUND = 'EVENT_DEVICE_FOUND',

  EVENT_SCANNING_TIMEOUT = 'EVENT_SCANNING_TIMEOUT',

  EVENT_SET_GROUP_SUCCESS = 'EVENT_SET_GROUP_SUCCESS',

  EVENT_SET_GROUP_FAILED = 'EVENT_SET_GROUP_FAILED',

  EVENT_SET_SCENE_SUCCESS = 'EVENT_SET_SCENE_SUCCESS',

  EVENT_SET_SCENE_FAILED = 'EVENT_SET_SCENE_FAILED',

  EVENT_DEVICE_STATUS = 'EVENT_DEVICE_STATUS',

  EVENT_DEVICE_ONLINE = 'EVENT_DEVICE_ONLINE',

  EVENT_BINDING_SUCCESS = 'EVENT_BINDING_SUCCESS',

  EVENT_NODE_RESET_SUCCESS = 'EVENT_NODE_RESET_SUCCESS',

  EVENT_NODE_RESET_FAILED = 'EVENT_NODE_RESET_FAILED',

  EVENT_ANDROID_SCAN_FINISH = 'EVENT_ANDROID_SCAN_FINISH',

  EVENT_TYPE_NOTIFICATION_MESSAGE_UNKNOWN = 'EVENT_TYPE_NOTIFICATION_MESSAGE_UNKNOWN',

  EVENT_TYPE_OTA_FAIL = 'EVENT_TYPE_OTA_FAIL',

  EVENT_TYPE_OTA_SUCCESS = 'EVENT_TYPE_OTA_SUCCESS',

  EVENT_TYPE_OTA_PROGRESS = 'EVENT_TYPE_OTA_PROGRESS',
}
